In [1]:
import torch
import numpy as np

# Tensor

## Task 1.1: Tạo Tensor

In [2]:
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")
# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")
# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.4804, 0.0621],
        [0.3955, 0.9323]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## Task 1.2: Các phép toán trên Tensor

In [3]:
x_data = torch.tensor([[1., 2.],
                       [3., 4.]])

sum_data = x_data + x_data
multi_data = x_data * 5
multi_transpose_data = x_data @ x_data.T

print(f'Tổng của data với data \n{sum_data}')
print(f'Tích của data với 5 \n{multi_data}')
print(f'Tích của data với data transpose \n {multi_transpose_data}')

Tổng của data với data 
tensor([[2., 4.],
        [6., 8.]])
Tích của data với 5 
tensor([[ 5., 10.],
        [15., 20.]])
Tích của data với data transpose 
 tensor([[ 5., 11.],
        [11., 25.]])


## Task 1.3: Indexing và Slicing

In [4]:
print(f'Hàng đầu tiên \n {x_data[0]}')
print(f'Cột thứ 2 \n {x_data[:,1]}')
print(f'Lấy ra giá trị hàng 2 cột 2 \n {x_data[1,1]}')

Hàng đầu tiên 
 tensor([1., 2.])
Cột thứ 2 
 tensor([2., 4.])
Lấy ra giá trị hàng 2 cột 2 
 4.0


## Task 1.4: Thay đổi shape

In [5]:
x = torch.rand(4,4)
x.view(16,1)

tensor([[0.6877],
        [0.0991],
        [0.4962],
        [0.1914],
        [0.8055],
        [0.4395],
        [0.0680],
        [0.5324],
        [0.1250],
        [0.1535],
        [0.3794],
        [0.5818],
        [0.9364],
        [0.8480],
        [0.6952],
        [0.6112]])

# Tính đạo hàm với autograd

## Task 2.1: Thực hành với autograd

In [6]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")
# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")
# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")
# Thực hiện thêm các phép toán
z = y * y * 3
# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))
# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x:{x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x0000022EFA730EE0>
Đạo hàm của z theo x:tensor([18.])


In [7]:
# Gọi z backward lần nữa
z.backward()
print(f"Đạo hàm của z theo x:{x.grad}")

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

Nếu gọi z.backward() sẽ bị lỗi do z được giải phóng nên không thể backward được nữa, nếu muốn backward tiếp thì phải cho retain_graph = True

In [8]:
z = y * y * 3
z.backward(retain_graph=True)
z.backward()
print(f"Đạo hàm của z theo x:{x.grad}")

Đạo hàm của z theo x:tensor([54.])


# 3. Xây dựng Mô hình đầu tiên với torch.nn

## Task 3.1: Lớp nn.Linear

In [9]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều
# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 0.2194,  0.3182],
        [ 0.7783, -1.0021],
        [ 2.4159,  1.3737]], grad_fn=<AddmmBackward0>)


## Task 3.2: Lớp nn.Embedding

In [10]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])
# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-0.5989,  0.2662, -1.0692],
        [ 1.4945,  1.0252,  0.2876],
        [ 0.5150, -0.2423, -0.4205],
        [ 0.0708,  1.6528,  0.3831]], grad_fn=<EmbeddingBackward0>)


## Task 3.3: Kết hợp thành 1 nn.Module

In [12]:
from torch import nn

In [13]:
class MyFirstModel(nn.Module):
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
    super(MyFirstModel, self).__init__()
    # Định nghĩa các lớp (layer) bạn sẽ dùng
    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.linear = nn.Linear(embedding_dim, hidden_dim)
    self.activation = nn.ReLU() # Hàm kích hoạt
    self.output_layer = nn.Linear(hidden_dim, output_dim)

  def forward(self, indices):
    # Định nghĩa luồng dữ liệu đi qua các lớp
    # 1. Lấy embedding
    embeds = self.embedding(indices)
    # 2. Truyền qua lớp linear và hàm kích hoạt
    hidden = self.activation(self.linear(embeds))
    # 3. Truyền qua lớp output
    output = self.output_layer(hidden)
    return output

# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
